spring:
  application:
    name: query-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/querydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: password



# HTTP Server
server:
  port: 8084   # HTTP (Tomcat) port




      
      
axon:

  kafka:
    #client-id: query
    default-topic: axon-events
    consumer:
      group-id: query-group
      bootstrap-servers: 192.168.99.100:9092
      event-processor-mode: tracking
  distributed:
    enabled: true
  serializer:
    messages: xstream
  eventhandling:
    processors:
      query:
        mode: tracking
        source: streamableKafkaMessageSource      